In [5]:
# Cell 1: Import Required Libraries
import pandas as pd
import numpy as np
import plotly.express as px
from datetime import timedelta
from helpermodules import memory_handling as mh

In [6]:
# Cell 2: Load the preprocessed data
pickle_helper = mh.PickleHelper.pickle_load('fedspeeches_preprocessed')
speeches_df = pickle_helper.obj
speeches_df

,date,speaker,title,link,text,timestamp,text_by_minute
0,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:00:00-05:00,The emergence of China as a global economic po...
1,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:01:00-05:00,"had reached seventy-one years, the infant mort..."
2,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:02:00-05:00,progress: Markets and productivityEconomists a...
3,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:03:00-05:00,"but steadily, away from central planning and t..."
4,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:04:00-05:00,information about supply and demand conditions...
...,...,...,...,...,...,...,...
24310,2024-01-08,Governor Michelle W. Bowman,New Year’s Resolutions for Bank Regulatory Pol...,/newsevents/speech/bowman20240108a.htm,It is a pleasure to join you this afternoon fo...,2024-01-08 10:24:00-05:00,"the requirements are spelled out in public, in..."
24311,2024-01-08,Governor Michelle W. Bowman,New Year’s Resolutions for Bank Regulatory Pol...,/newsevents/speech/bowman20240108a.htm,It is a pleasure to join you this afternoon fo...,2024-01-08 10:25:00-05:00,assumptions. Transparency allows bankers to un...
24312,2024-01-08,Governor Michelle W. Bowman,New Year’s Resolutions for Bank Regulatory Pol...,/newsevents/speech/bowman20240108a.htm,It is a pleasure to join you this afternoon fo...,2024-01-08 10:26:00-05:00,"standards. To the contrary, it means that we s..."
24313,2024-01-08,Governor Michelle W. Bowman,New Year’s Resolutions for Bank Regulatory Pol...,/newsevents/speech/bowman20240108a.htm,It is a pleasure to join you this afternoon fo...,2024-01-08 10:27:00-05:00,"this process, by sharing your views and concer..."
24314,2024-01-08,Governor Michelle W. Bowman,New Year’s Resolutions for Bank Regulatory Pol...,/newsevents/speech/bowman20240108a.htm,It is a pleasure to join you this afternoon fo...,2024-01-08 10:28:00-05:00,my colleagues on the Federal Open Market Commi...

In [7]:
# Cell 3: Load Governors List
# Load the list of governors from a .txt file
with open("speakers.txt", "r") as f:
    governors = eval(f.read())  # Assuming the file contains a Python list

# Filter speeches by governors
filtered_speeches = speeches_df[speeches_df['speaker'].isin(governors)]
print(f"Number of speeches by governors: {len(filtered_speeches)}")
filtered_speeches

Number of speeches by governors: 10971

,date,speaker,title,link,text,timestamp,text_by_minute
0,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:00:00-05:00,The emergence of China as a global economic po...
1,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:01:00-05:00,"had reached seventy-one years, the infant mort..."
2,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:02:00-05:00,progress: Markets and productivityEconomists a...
3,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:03:00-05:00,"but steadily, away from central planning and t..."
4,2006-12-15,Chairman Ben S. Bernanke,The Chinese Economy: Progress and Challenges,/newsevents/speech/bernanke20061215a.htm,The emergence of China as a global economic po...,2006-12-15 10:04:00-05:00,information about supply and demand conditions...
...,...,...,...,...,...,...,...
15708,2017-04-04,Governor Daniel K. Tarullo,Departing Thoughts,/newsevents/speech/tarullo20170404a.htm,Tomorrow is my last day at the Federal Reserve...,2017-04-04 10:52:00-04:00,giving the firms the model will likely encoura...
15709,2017-04-04,Governor Daniel K. Tarullo,Departing Thoughts,/newsevents/speech/tarullo20170404a.htm,Tomorrow is my last day at the Federal Reserve...,2017-04-04 10:53:00-04:00,"model in the hands of the GSEs, even a scenari..."
15710,2017-04-04,Governor Daniel K. Tarullo,Departing Thoughts,/newsevents/speech/tarullo20170404a.htm,Tomorrow is my last day at the Federal Reserve...,2017-04-04 10:54:00-04:00,some granularity in the definition of asset ca...
15711,2017-04-04,Governor Daniel K. Tarullo,Departing Thoughts,/newsevents/speech/tarullo20170404a.htm,Tomorrow is my last day at the Federal Reserve...,2017-04-04 10:55:00-04:00,have liked to touch upon important topics such...
15712,2017-04-04,Governor Daniel K. Tarullo,Departing Thoughts,/newsevents/speech/tarullo20170404a.htm,Tomorrow is my last day at the Federal Reserve...,2017-04-04 10:56:00-04:00,lessons of the financial crisis were forgotten...

In [3]:
from dotenv import load_dotenv
import os

# Load environment variables from the .env file
load_dotenv(dotenv_path='./api.env')  # Specify path if it's in a different directory
# Access the Twelve Data API key
api_key = os.getenv("API_KEY")

In [23]:
# Step 1: Ensure the timestamp column is in datetime format (if it's not already)

df = filtered_speeches.copy()
# Step 1: Extract the date part from the timestamp (already done in your code)
df['speech_date'] = df['timestamp'].dt.date

# Step 2: Group by 'speech_date' and find the first and last timestamps for each speech
speech_dates_df = df.groupby('speech_date').agg(
    start_time=('timestamp', 'min'),
    end_time=('timestamp', 'max')
).reset_index()

# Step 3: Display the resulting dataframe with speech dates and their respective start and end times
speech_dates_df

    speech_date                start_time                  end_time
0    2006-01-18 2006-01-18 10:00:00-05:00 2006-01-18 10:18:00-05:00
1    2006-02-02 2006-02-02 10:00:00-05:00 2006-02-02 11:00:00-05:00
2    2006-02-06 2006-02-06 10:00:00-05:00 2006-02-06 10:03:00-05:00
3    2006-02-23 2006-02-23 10:00:00-05:00 2006-02-23 10:20:00-05:00
4    2006-02-24 2006-02-24 10:00:00-05:00 2006-02-24 10:49:00-05:00
..          ...                       ...                       ...
379  2016-07-12 2016-07-12 10:00:00-04:00 2016-07-12 10:14:00-04:00
380  2016-09-26 2016-09-26 10:00:00-04:00 2016-09-26 10:56:00-04:00
381  2016-10-21 2016-10-21 10:00:00-04:00 2016-10-21 10:34:00-04:00
382  2016-12-02 2016-12-02 10:23:00-05:00 2016-12-02 11:06:00-05:00
383  2017-04-04 2017-04-04 10:00:00-04:00 2017-04-04 10:56:00-04:00

[384 rows x 3 columns]